name: Deploy

on:
  schedule:
    - cron: '0 2 * * *'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.7

    - name: Set up Ruby
      uses: actions/setup-ruby@v1
      with:
        ruby-version: '2.6'

    - name: Install dependencies
      run: |
        pip install -r requirements.txt
        bundle install

    - name: Build
      env:
        JEKYLL_ENV: production
        INDIGO_API_AUTH_TOKEN: ${{ secrets.INDIGO_API_AUTH_TOKEN }}
      run: |
        python bin/update.py
        bundle exec jekyll build --trace

    - name: Deploy to gh-pages
      uses: JamesIves/github-pages-deploy-action@3.7.1
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        BRANCH: gh-pages
        FOLDER: _site/
        SINGLE_COMMIT: true
